name: "Generate an Artifact with ProdOps"
description: "Generate an Artifact with ProdOps"
author: ProdOps
branding:
  icon: "upload-cloud"
  color: "purple"
runs:
  using: "docker"
  image: "Dockerfile"
outputs:
  artifact_content:
    description: "The content of the generated artifact"
  artifact_url:
    description: "The URL of the generated artifact"
inputs:
  prodops_api_key:
    description: Your ProdOps API key
    required: true
  prodops_api_url:
    description: The ProdOps API endpoint to use. Defaults to https://app.prodops.ai
    required: false
  project_id:
    description: The ID of the ProdOps project to generate your artifact in
    required: true
  artifact_type_slug:
    description: TODO
    required: true
  prompt_template_id:
    description: The ID of the prompt template to use
    required: true
  input_count:
    description: TODO
    required: true
  input_1_name:
    description: TODO
    required: false
  input_1_value:
    description: TODO
    required: false
  input_2_name:
    description: TODO
    required: false
  input_2_value:
    description: TODO
    required: false
  input_3_name:
    description: TODO
    required: false
  input_3_value:
    description: TODO
    required: false
  input_4_name:
    description: TODO
    required: false
  input_4_value:
    description: TODO
    required: false
  input_5_name:
    description: TODO
    required: false
  input_5_value:
    description: TODO
    required: false
